### ISSUE TITLE
Failed test 'No tests run for subtest "Build a basic dist"'

### ISSUE THREAD

**Issue by eserte** [GrantStreetGroup/p5-Dist-Zilla-PluginBundle-Author-GSG#1]
On some of my smoker systems t/Dist-Zilla-PluginBundle-Author-GSG.t fails:
```
...
    # No tests run!

#   Failed test 'No tests run for subtest "Build a basic dist"'
#   at t/Dist-Zilla-PluginBundle-Author-GSG.t line 110.
[DZ] no version was ever set at inline delegation in Dist::Zilla for logger->log_fatal (attribute declared in /usr/perl5.18.4p/lib/site_perl/5.18.4/Dist/Zilla.pm at line 768) line 18.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
t/Dist-Zilla-PluginBundle-Author-GSG.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests 
...
```

**Comment by afresh1** [comment]
This also seems like it might be a git problem.  Although I don't expect anyone outside of GSG to actually use this module I'd like to at least understand why they are failing, even if all I can do is detect the situation and skip testing.

What sort of details can you provide me about the systems that it fails on so I could possibly reproduce?

**Comment by eserte** [comment]
Maybe it's a git problem, but not related to a particular git version. For example looking at http://matrix.cpantesters.org/?dist=Dist-Zilla-PluginBundle-Author-GSG%200.0.7;os=freebsd;reports=1#sl=2,1 it seems that freebsd versions 9, 12, and 13 are fine, and 10 and 11 are failing. But (at least on my smokers) 9 and 10 have the same git version (2.11.0) and 11, 12 and 13 have also the same version (2.21.0), but different results.

Unfortunately statistical analysis also does not give any clues (which would be something with R^2=1 not being the trivial fact that something failed):
http://analysis.cpantesters.org/solved?distv=Dist-Zilla-PluginBundle-Author-GSG-0.0.7

**Comment by afresh1** [comment]
[This regression in that analysis you linked](http://analysis.cpantesters.org/reports_by_field?distv=Dist-Zilla-PluginBundle-Author-GSG-0.0.7;field=qr%3A%28Can%27t%20locate%20object%20method%20.%2B%29) seems to point towards [this PR](https://github.com/ghedo/p5-Dist-Zilla-Plugin-GitHub/pull/52) and that I need to require [version 0.46 that fixed the issue](https://metacpan.org/changes/distribution/Dist-Zilla-Plugin-GitHub).  I do see in [one of the failing smokes, picked at random](http://www.cpantesters.org/cpan/report/5c506c4e-8479-11e9-9f38-21291f24ea8f) that it is using 0.45.

**Comment by afresh1** [comment]
Bummer, requiring 0.46 doesn't seem to have solved either issue.  I'll have to think harder about how to determine what is going wrong and add more diagnostics to the tests.

**Comment by afresh1** [comment]
Good news, I figured out how to build git 1.7.1 and can reproduce this failure as well.

**Comment by afresh1** [comment]
Hurray! Finally figured out which dependency it was! Now with [`requires 'Dist::Zilla::Plugin::OurPkgVersion', '0.20'; `](https://github.com/GrantStreetGroup/p5-Dist-Zilla-PluginBundle-Author-GSG/commit/5679bca0a8e7dab0ce8d9e8754787428db8dd3d0), we now [have a passing result](http://www.cpantesters.org/cpan/report/47ffa382-f99e-11e9-89d4-81dc0ab3ecc5) where we [used to have a failure](http://www.cpantesters.org/cpan/report/f00d3804-f698-11e9-b003-71353384a6e2).
