### ISSUE TITLE
Failed test 'Correct default license year'

### ISSUE THREAD

**Issue by eserte** [GrantStreetGroup/p5-Dist-Zilla-PluginBundle-Author-GSG#2]
On my CentOS6 smokers t/Dist-Zilla-Plugin-Author-GSG.t fails:
```
...
    #   Failed test 'Correct default license year'
    #   at t/Dist-Zilla-Plugin-Author-GSG.t line 62.
    #          got: '2019'
    #     expected: '2001 - 2019'
    # Looks like you failed 1 test of 4.

#   Failed test 'Dist with defaults'
#   at t/Dist-Zilla-Plugin-Author-GSG.t line 63.
# Looks like you failed 1 test of 4.
t/Dist-Zilla-Plugin-Author-GSG.t ........ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
...
```

**Comment by afresh1** [comment]
I have seen this error in the smokers, but haven't yet figured out what in the system causes it.  I thought I had determined and worked around this failure, but obviously not.  What version of git, if any, is available while that test is failing?

**Comment by eserte** [comment]
The CentOS6 smoker reports:
```$ git --version
git version 1.7.1
```
Which is the oldest git I have available on my smokers. The next newer is 1.7.10.4 (Debian/wheezy) and does not have this particular problem.

**Comment by afresh1** [comment]
Well, I've solved this one.  `git name-rev` only got [support for `--max-parents` in 1.7.5-rc0](https://github.com/git/git/commit/ad5aeeded3295589b2573b143f754762a56f8f82), so I'll need to add some validation to the tests and probably some additional complaints about the git version [where we require that flag](https://github.com/GrantStreetGroup/p5-Dist-Zilla-PluginBundle-Author-GSG/blob/master/lib/Dist/Zilla/Plugin/Author/GSG.pm#L24).

**Comment by eserte** [comment]
I don't see this failure anymore with 0.0.11.
